FROM python:3
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
WORKDIR /app
COPY requirement.txt /app/
RUN pip install --upgrade pip
RUN pip install -r requirement.txt
COPY . /app/



# FROM python:alpine
# ENV PYTHONDONTWRITEBYTECODE=1
# ENV PYTHONUNBUFFERED=1
# ENV DJANGO_SUPERUSER_PASSWORD=admin

# WORKDIR /app

# RUN apk update
# RUN apk add  --no-cache gcc python3-dev musl-dev mariadb-dev

# RUN pip install --upgrade pip
# ADD requirement.txt .
# RUN pip install -r requirement.txt

# RUN apk del gcc python3-dev musl-dev

# CMD while ! python3 manage.py sqlflush > /dev/null 2>&1 ; do sleep 1 ; done && \
#     python manage.py makemigrations --noinput && \
#     python3 manage.py migrate --noinput && \
#     python manage.py migrate --noinput && \
#     python manage.py createsuperuser --user admin --email mohammad.r.yazdaniyan@gmail.com --noinput; \
#     # gunicorn -b 0.0.0.0:8000 config.wsgi
#     python manage.py runserver 0.0.0.0:8000